version: '3.8'

services:
  warehouse-service:
    image: warehouse-service:latest
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - rabbitmq

  storefront-service:
    image: storefront-service:latest
    build:
      context: ./storefront-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

networks:
  default:
    driver: bridge