spring:
  application:
    name: storefront-service

server:
  port: 8081

logging:
  level:
    root: INFO
    com.example.storefront: DEBUG

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storefront_db
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

# RabbitMQ configuration
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# JPA/Hibernate configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Other configurations
storefront:
  some-custom-property: value